### ISSUE TITLE
IllegalArgumentException: Supplied X509TrustManager does not implement X509Extensions contract

### ISSUE THREAD

**Issue by AndrewJack** [commonsguy/cwac-netsecurity#1]
**Android versions**: 5 and 6 (any back ported version?) (Cannot reproduce on an emulator)
**Reproducible devices**: Nexus 5X, Nexus 5, Samsung S6, MotoG3

**Steps / Code to reproduce**: 
1. Run the demo app and read the exception from [this line](https://github.com/commonsguy/cwac-netsecurity/blob/master/demo/src/main/java/com/commonsware/cwac/netsecurity/demo/QuestionsFragment.java#L68)
2. Use a Reproducible device on a back ported version (< 7)

**Exception**:
```
Fatal Exception: java.lang.IllegalArgumentException: Supplied X509TrustManager does not implement X509Extensions contract
       at com.commonsware.cwac.netsecurity.X509ExtensionsWrapper.<init>(X509ExtensionsWrapper.java:53)
       at com.commonsware.cwac.netsecurity.CompositeTrustManager.add(CompositeTrustManager.java:120)
       at com.commonsware.cwac.netsecurity.TrustManagerBuilder.add(TrustManagerBuilder.java:116)
       at com.commonsware.cwac.netsecurity.TrustManagerBuilder.withConfig(TrustManagerBuilder.java:252)
       at com.commonsware.cwac.netsecurity.TrustManagerBuilder.withManifestConfig(TrustManagerBuilder.java:243)
```

**Comment by AndrewJack** [comment]
I found this is actually caused by proguard stripping some of the files that use reflection.

Added the following, which resolved this crash:
```
-keep class com.commonsware.cwac.netsecurity.** { *; }
```

More precise proguard rules would be great 👍

**Comment by Jonathan727** [comment]
> More precise proguard rules would be great 👍

I have the proguard rule narrowed to:

```
-keepclassmembers class com.commonsware.cwac.netsecurity.** implements javax.net.ssl.X509TrustManager {
    public *;
}
```
