### ISSUE TITLE
Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by Mahtalitet** [commonsguy/cwac-netsecurity#7]
I think, stack trace is an enough info to fix it, if not - I will expand description of this issue. Thanks.

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                       java.lang.Throwable: Explicit termination method 'close' not called
                                                                           at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                           at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                           at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.CertPinManager.readPinFile(CertPinManager.java:146)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.CertPinManager.ensureInitialized(CertPinManager.java:97)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.CertPinManager.lookup(CertPinManager.java:162)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.CertPinManager.isChainValid(CertPinManager.java:77)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:638)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:506)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:526)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:463)
                                                                           at com.commonsware.cwac.netsecurity.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:319)
                                                                           at com.commonsware.cwac.netsecurity.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:114)
                                                                           at com.commonsware.cwac.netsecurity.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:161)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.commonsware.cwac.netsecurity.X509ExtensionsWrapper.checkServerTrusted(X509ExtensionsWrapper.java:78)
                                                                           at com.commonsware.cwac.netsecurity.CompositeTrustManager.checkServerTrusted(CompositeTrustManager.java:252)
                                                                           at com.commonsware.cwac.netsecurity.CompositeTrustManager.checkServerTrusted(CompositeTrustManager.java:232)
                                                                           at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:117)
                                                                           at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
                                                                           at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                           at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                           at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
                                                                           at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
                                                                           at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
                                                                           at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
                                                                           at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
                                                                           at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                           at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at com.commonsware.cwac.netsecurity.OkHttp3Integrator$X509Interceptor.intercept(OkHttp3Integrator.java:65)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
```

**Comment by commonsguy** [comment]
Addressed in v0.3.1 -- thanks for pointing this out!
